# 指定语言环境
language: node_js
# 指定需要sudo权限
sudo: false # required
# 指定node_js版本
node_js: 
  - 12
# 指定缓存模块，可选。缓存可加快编译速度。
cache: 
  directories:
    - node_modules

# 指定博客源码分支，因人而异。hexo博客源码托管在独立repo则不用设置此项
branches:
  only:
    - main 

before_install:
  - npm install -g yarn

# Start: Build Lifecycle

install:
  - yarn

# 执行清缓存，生成网页操作
script:
  - yarn build

# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后deploy部署
after_script:
  

# End: Build LifeCycle

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  local-dir: ./build
  keep-history: true
  on:
    branch: main
  local-dir: public
